version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./app:/app:cached
    command: sh -c "npm run dev"
    environment:
      - HOST=0.0.0.0
    ports:
      - "3001:3000"